[package]
name = "mqdemo"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.1", features = ["full"] }
MQExtensionLib = {path="../../Common/MQExtensionLib"}
CommonExtensionLib = {path="../../Common/CommonExtensionLib"}
