[package]
name = "CacheExtensionLib"
version = "0.1.0"
edition = "2021"

[dependencies]
deadpool-redis = { version = "0.17.0", features = ["serde"] }
lazy_static = "1.5.0"
redis = { version = "0.26.1", features = ["tokio-comp"] }
